// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  image: dynamic(() => import("./Image")),
  image_cards: dynamic(() => import("./ImageCards")),
  parallax_hero: dynamic(() => import("./ParallaxHero")),
  quote: dynamic(() => import("./Quote")),
  text: dynamic(() => import("./Text")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
